# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-04-17T23:17:17+00:00

from __future__ import annotations

from typing import Optional

from pydantic import AnyUrl, BaseModel, EmailStr


class UserRegisterRequest(BaseModel):
    username: str
    email: EmailStr
    password: str


class UserLoginRequest(BaseModel):
    username: str
    password: str


class UserResponse(BaseModel):
    user_id: str
    username: str
    email: str


class LoginResponse(BaseModel):
    access_token: str
    token_type: str


class ProjectCreateRequest(BaseModel):
    name: str
    description: Optional[str] = None


class ProjectResponse(BaseModel):
    project_id: str
    name: str
    description: Optional[str] = None


class ProjectListResponse(BaseModel):
    projects: list[ProjectResponse]


class TaskStatusResponse(BaseModel):
    task_id: str
    status: str
    result: Optional[str] = None


class WebhookRegisterRequest(BaseModel):
    url: AnyUrl
    event: str


class WebhookResponse(BaseModel):
    webhook_id: str
    url: AnyUrl
    event: str


class WebsiteAnalyticsResponse(BaseModel):
    website_id: str
    visits: int
    bounce_rate: float
    avg_time_on_site: float


class WebsiteMonetizationResponse(BaseModel):
    website_id: str
    revenue: float
    currency: str
    sources: list[str]


class LLMProviderSwitchRequest(BaseModel):
    provider: str  # Example: "openrouter" or "gemini"


class MessageResponse(BaseModel):
    message: str  # A simple response message


class ErrorResponse(BaseModel):
    error: str  # A simple error message


class NicheDiscoveryRequest(BaseModel):
    keywords: list[str]  # List of keywords to analyze for niche opportunities


class NicheDiscoveryResponse(BaseModel):
    niches: list[str]  # List of discovered niche opportunities
    suggestions: list[str]  # List of suggestions for niche development


class DailyNicheReportResponse(BaseModel):
    date: str  # Date of the report
    niches: list[str]  # List of niches reported
    insights: list[str]  # Insights and trends observed


class WebsiteCreationRequest(BaseModel):
    domain: str  # Domain name for the website
    template: str  # Template to use for the website
    content: str  # Initial content for the website


class WebsiteCreationResponse(BaseModel):
    website_id: str  # Unique identifier for the created website
    domain: str  # Domain name for the website
    template: str  # Template used for the website
    content: str  # Initial content for the website


class WebsiteMimicRequest(BaseModel):
    target_website: str  # URL of the website to mimic
    domain: str  # Domain name for the new website
    template: str  # Template to use for the new website
    content: str  # Initial content for the new website


class WebsiteIdentifierRequest(BaseModel):
    website_id: str  # Unique identifier for the website


class WebsiteViewResponse(BaseModel):
    website_id: str  # Unique identifier for the website
    domain: str  # Domain name for the website
    template: str  # Template used for the website
    content: str  # Initial content for the website
    analytics: WebsiteAnalyticsResponse  # Analytics data for the website
    monetization: WebsiteMonetizationResponse  # Monetization data for the website


class WebsiteStatusResponse(BaseModel):
    website_id: str  # Unique identifier for the website
    status: str  # Current status of the website (e.g., "active", "inactive", "under_maintenance")
